### ISSUE TITLE
Kaspersky freaks out over the exe file in Windows

### ISSUE THREAD

**Issue by regstuff** [c9fe/22120#125]
Gives the following error when I download the exe. Won't even let me run the file.
Windows info: Microsoft Windows [Version 10.0.18363.1440]
(c) 2019 Microsoft Corporation
Kaspersky Info: Kaspersky Endpoint Security 11.8.0.384

![kaspersky warning](https://user-images.githubusercontent.com/6016831/172436312-3bef23fb-f6cd-45fd-9c00-7740e01d525d.png)

**Comment by crisdosaygo** [comment]
Interesting. I'm not sure I have that guy installed, but I would always have to add exception to Symantec endpoint exception to run it. Plus for the firewall. Main issue is it's unsigned. 

**I have a feeling the next time I do a build, it may have changed the file enough that this is not an issue.**

The false positive is maybe caused by how I think pkg compresses some assets (or even the node binary) so whatever fingerprint that these security tests use, it must be triggering that. 

Worst case is some bad actor actually compromised github releases and inserted a Torjan into these binaries. I doubt as this project has a relatively small number of downloads, plus this would likely affect many many projects...but cannot rule it out.

If any security experts out there want to take a look at the binary more closely in isolation, that could be cool.

**Comment by crisdosaygo** [comment]
Thanks @regstuff for the report. Sorry you have not been able to run it!
