### ISSUE TITLE
"Normal Browsing" mode

### ISSUE THREAD

**Issue by yamrzou** [c9fe/22120#48]
First, thanks a lot for open sourcing this. The direct integration with the browser is brilliant, it makes archiving effortless.

I noticed that pages load slightly slower when the browser is controlled with this app. I might be wrong as I didn't do any measurement, but wondering if some settings make it so? If that's the case I'd like to propose a "Normal Browsing" mode, i.e. saving is disabled and the app doesn't tweak or interfere with the browser unless the save mode is enabled. That would also allow saving only the pages I care about.

**Comment by cris691** [comment]
Yeah this is a good idea. pages do load slower, not just because saves are happening, but because we switch off cache to make saving reproducible, and sometimes the entire thing is reloaded because the debugger couldn't attach fast enough to intercept the first requests in the case of a new tab, which is an open bug in Chrome.

Thanks for the suggestion. I'm not sure how to enable save only what you want. I know it's not your job and I'm sorry for making this big ask but would be impossible you to suggest some UI ideas or mockup or UX advice here?

**Comment by c9fe** [comment]
I've decided this is no good. Not going to do it.
