### ISSUE TITLE
Misrepresentation of the WARC format

### ISSUE THREAD

**Issue by JustAnotherArchivist** [c9fe/22120#63]
(Disclaimer: I don't have any experience with this project. A link was shared on ArchiveTeam's IRC, I skimmed over the readme and came across this gross inaccuracy there, and that's why I'm filing this issue.)

The readme claims:

> Why not WARC [...]?
>
> Other formats save translations of the resources you archive.
> [...]
> Both WARC and MHTML require mutilatious modifications of the resources so that the resources can be "forced to fit" the format.

This is simply not true. WARC does not modify the data in any way at all. It stores the raw HTTP requests and responses, including even chunked transfer encoding. All it does is add a layer of metadata around the HTTP requests/responses, using a very similar structure as HTTP. Of course, there might be software which does modify the data and hence writes invalid WARCs, but that's not what you're saying and completely irrelevant in this context anyway.

On a related note, are you preserving chunked transfer encoding, exact headers as sent by the server, trailers, multi-part encoding, etc.? Based on a quick glance over the source code, it appears that you're using Chromium's DevTools protocol, and to my knowledge, that only provides normalised headers and a TE-decoded body. (I don't know what it does with trailers and multi-part encoding.)

**Comment by c9fe** [comment]
Thanks, I'll take a look

**Comment by c9fe** [comment]
Hey @JustAnotherArchivist if you take a look now and let me know how you feel about it I might consider what you say. 

I really appreciate your help with this section

**Comment by gildas-lormeau** [comment]
Hey @c9fe, to be honest, I was a bit surprised by the fact that you oppose your project with SingleFile. From my point of view, these 2 projects are complementary and do really not serve the same purpose.

SingleFile was not created based on right or wrong beliefs. SingleFile was created in 2010 on Chrome, because at that time, no acceptable solution existed to save pages in this browser. I chose the HTML format because I had absolutely no other choice, from a technical point of view. It was purely pragmatic and it remains so.
However, I don't regret it. The main advantage of the HTML format is the fact that in 20-30 years, you should be able to read a SingleFile archive using only *one software*: the web browser. What's the point of saving a page in a given (and possibly proprietary) format if you can't restore it when you need to view it?

Thus, I think it could be more interesting for your audience to compare your format with formats that compete with yours:
 - WARC
 - HAR
 - MHTML (maybe MAF?)
 - Web bundles

It might also be more appropriate to compare your project to:
 - Conifer/Webrecorder
 - Proxies like Squid
 - Offline navigation feature already available in some browsers like Firefox

**Comment by pirate** [comment]
I agree with @gildas-lormeau in that the choice of comparing 22120 to SingleFile, ArchiveBox, etc. is strange, as the approaches are tangential, not necessarily competing. Proxy archiving is a fundamentally different space than content archiving.

ArchiveBox is almost agnostic to the actual method used to save the page, it supports a dozen different extractor types, but the entire program can be run through a proxy archiver that saves the requests verbatim (I do this with pywb). The DOM dump from the chrome extractor also saves the viewed page verbatim with no content rewriting at all (and it sucks for that reason, you need *some* rewriting for a good replay experience).

The project you should really compare with is Conifer/Webrecorder, because it uses a highly established format (WARC) that's been developed for *decades* for the sole purpose of reproducing HTTP traffic with the highest fidelity. It supports both verbatim saving and content rewriting *on view* (meaning on disk it's always exactly as recorded). Fundamentally there are sites you will not be able to replay properly without some form of content rewriting. These include things with websockets, webrtc, audio, video, dynamic requests with side effects, etc. of which the web is full of. There is a small army of people working to push WARC towards being able to store these things, so in my mind having a proxy archiver tool that actively eschews WARC is a big downside, because you lose out on the community support and long-term durability of a format supported by many more tools.

**Comment by c9fe** [comment]
It's so hilarious you both now come here to speak up, and to complain about comparing 22120 to your products after you come to the 22120 Show HN 2 days ago to compare your products, ArchiveBox and SingleFile, with 22120. 🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣 

Thank you for a great laugh today
