### ISSUE TITLE
UX Consideration: Showing Page Save Progress

### ISSUE THREAD

**Issue by johnhorsema** [c9fe/22120#94]
This is a slight issue upon using DiskerNet:

When user visits URLs via Chrome, DiskerNet intercepts the requests and shows its progress by the loading indicator of the Chrome tab.

Is there a better UX to show page save progress instead of relying on checking each and every tab? i.e. show total pages captured vs pages intercepting

Furthermore, I came across [this](https://archiveweb.page/en/features/autopilot/). Would there be a possibility for similar feature within DiskerNet. I know it sort of becomes a scraping tool when this is introduced, but it will be useful for users to archive sites/content that are close to be taken down.

**Comment by crisdosaygo** [comment]
I see what your saying, I think. Both things you mentioned:

- summary loading progress indicators
- automated browsing while archiving

sound more like they are about doing stuff in bulk, or quickly, rather than creating a personal archive for yourself to use. Let's call this "Bulk Automated Archiving" (or Baa, or the 🐑 feature, because sheep go baaa right? 😉 )

As such it's not really in scope for this project I think, as much as I appreciate the use cases, and appreciate you checking out my competitors and giving me intel on what they are up to -- and suggesting to bring that here, I do really appreciate that, that's really great! If you keep that up, I'll love that ❤️ 

So what I'll do is I'll hit pause on these concepts (the 🐑 features) for now, so I create some time away from them where I consider, "Am I going to think about them some more here or not?" 

And maybe I'll update this. 

I appreciate your good ideas tho. Maybe if you post again, you can share more about some things you specifically are trying to do...that might help contextualize what you say for me, as well as provide more opportunity for even more ideas to come out--from you me, or others.

So I think your comments are really on point, I really appreciate them, and I do really like your ideas tho, they're really good, so thanks very much for contributing! 👍🏻 ⭐ 😌
